<a href="https://colab.research.google.com/github/jahnavineelam/DeepLearning_Neural_Networks/blob/main/DL_LAB3_23035/exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Input
x = np.array([1, 0])

# Target
y = 1

# Input → Hidden Weights
W1 = np.array([
    [0.2, 0.3],
    [0.4, 0.1]
])

# Hidden → Output Weights
W2 = np.array([
    [0.5],
    [0.6]
])

learning_rate = 0.1

# Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Sigmoid Derivative
def sigmoid_derivative(x):
    return x * (1 - x)

# -----------------------------
# Forward Propagation
# -----------------------------

hidden_input = np.dot(x, W1)

hidden_output = sigmoid(hidden_input)

output_input = np.dot(hidden_output, W2)

predicted_output = sigmoid(output_input)

loss = 0.5 * (y - predicted_output[0])**2

print("Hidden Layer Output")
print(hidden_output)

print("\nPredicted Output")
print(predicted_output)

print("\nLoss")
print(loss)

Hidden Layer Output
[0.549834   0.57444252]

Predicted Output
[0.65012359]

Loss
0.06120675087427858


In [ ]:
# -----------------------------
# Backpropagation
# -----------------------------

output_delta = (predicted_output - y) * sigmoid_derivative(predicted_output)

hidden_delta = output_delta.dot(W2.T) * sigmoid_derivative(hidden_output)

# Gradients
grad_W2 = hidden_output.reshape(-1,1) * output_delta

grad_W1 = np.outer(x, hidden_delta)

print("Output Delta")
print(output_delta)

print("\nHidden Delta")
print(hidden_delta)

print("\nGradient W2")
print(grad_W2)

print("\nGradient W1")
print(grad_W1)

Output Delta
[-0.07958391]

Hidden Delta
[-0.00984917 -0.01167297]

Gradient W2
[[-0.04375794]
 [-0.04571638]]

Gradient W1
[[-0.00984917 -0.01167297]
 [-0.         -0.        ]]


In [ ]:
# -----------------------------
# Weight Update
# -----------------------------

W2_new = W2 - learning_rate * grad_W2

W1_new = W1 - learning_rate * grad_W1

print("Updated W1")
print(np.round(W1_new,4))

print("\nUpdated W2")
print(np.round(W2_new,4))

Updated W1
[[0.201  0.3012]
 [0.4    0.1   ]]

Updated W2
[[0.5044]
 [0.6046]]
